dateModified: 1738871128
email:
  fromEmail: brian@pixelandtonic.com
  fromName: 'Vite Test'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  cloud:
    hasUrls: true
    name: Cloud
    settings:
      expires: '1 years'
      hasUrls: true
      localFsPath: '@webroot/uploads'
      localFsUrl: '@web/uploads'
      subpath: null
    type: craft\cloud\fs\AssetsFs
meta:
  __names__:
    09feb30b-590f-4389-b6b4-8f10505991ca: 'Vite Test' # Vite Test
    8944f82a-b403-42d1-81d2-3e6f900af0ce: 'Vite Test' # Vite Test
plugins:
  seomatic:
    edition: standard
    enabled: true
    licenseKey: T9DLMVD0LF5B4QZ7DUP0QR8R
    schemaVersion: 3.0.12
system:
  edition: pro
  live: true
  name: 'Vite Test'
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
